name: petrocardapppp
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.5.0
  http: ^1.0.0
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  flutter_onboarding_slider: ^1.0.11
  animate_do: ^3.0.2
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  loading_animation_widget: ^1.2.0+4
  flutter_slider_drawer: ^2.1.3
  flutter_card_swiper: ^7.0.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.7
  permission_handler: ^11.0.1
  mime: ^1.0.0
  http_parser: ^4.0.0
  card_loading: ^0.3.2
  photo_view: ^0.14.0
  intl: ^0.19.0
  url_launcher: ^6.1.13
  google_fonts: ^5.1.0
  awesome_notifications: ^0.9.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
  - assets/Animations/splashimage.png
  - assets/Animations/
  - assets/Icons/
  - assets/svgs/
fonts:
  - family: RobotoMono
    fonts:
          - asset: fonts/RobotoMono-Regular.ttf
          - asset: fonts/RobotoMono-Bold.ttf
            weight: 700
#  assets:
#    - images/a_dot_burr.jpeg
#    - images/a_dot_ham.jpeg
#
#  fonts:
#    - family: Schyler
#      fonts:
#        - asset: fonts/Schyler-Regular.ttf
#        - asset: fonts/Schyler-Italic.ttf
#          style: italic
#    - family: Trajan Pro
#      fonts:
#        - asset: fonts/TrajanPro.ttf
#        - asset: fonts/TrajanPro_Bold.ttf
#          weight: 700